PPAPI_FLASH_PATH="/usr/lib/pepperflashplugin-nonfree/libpepflashplayer.so"
PPAPI_FLASH_VERSION="20.0.0.306"

all: deploy

run:
	electron ../app --ppapi-flash-path=${PPAPI_FLASH_PATH} --ppapi-flash-version=${PPAPI_FLASH_VERSION}

deploy:
	echo "This should do the package wrapping/building"
